//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

const (
	SlackSignatureScopes slackSignatureContextKey = "SlackSignature.Scopes"
)

// Acknowledgement defines model for Acknowledgement.
type Acknowledgement struct {
	Challenge *string `json:"challenge,omitempty"`
}

// Envelope defines model for Envelope.
type Envelope struct {
	Challenge *string     `json:"challenge,omitempty"`
	Event     *SlackEvent `json:"event,omitempty"`
	EventId   *string     `json:"event_id,omitempty"`
	TeamId    *string     `json:"team_id,omitempty"`
	Type      string      `json:"type"`
}

// SlackEvent defines model for SlackEvent.
type SlackEvent struct {
	BotId           *string       `json:"bot_id,omitempty"`
	Channel         *string       `json:"channel,omitempty"`
	ChannelType     *string       `json:"channel_type,omitempty"`
	DeletedTs       *string       `json:"deleted_ts,omitempty"`
	Message         *SlackMessage `json:"message,omitempty"`
	PreviousMessage *SlackMessage `json:"previous_message,omitempty"`
	Subtype         *string       `json:"subtype,omitempty"`
	Text            *string       `json:"text,omitempty"`
	ThreadTs        *string       `json:"thread_ts,omitempty"`
	Ts              *string       `json:"ts,omitempty"`
	Type            string        `json:"type"`
	User            *string       `json:"user,omitempty"`
}

// SlackMessage defines model for SlackMessage.
type SlackMessage struct {
	BotId    *string `json:"bot_id,omitempty"`
	Subtype  *string `json:"subtype,omitempty"`
	Text     *string `json:"text,omitempty"`
	ThreadTs *string `json:"thread_ts,omitempty"`
	Ts       *string `json:"ts,omitempty"`
	User     *string `json:"user,omitempty"`
}

// slackSignatureContextKey is the context key for SlackSignature security scheme
type slackSignatureContextKey string

// SlackEventParams defines parameters for SlackEvent.
type SlackEventParams struct {
	XSlackRequestTimestamp string `json:"X-Slack-Request-Timestamp"`
}

// SlackEventJSONRequestBody defines body for SlackEvent for application/json ContentType.
type SlackEventJSONRequestBody = Envelope

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /livez)
	Live(w http.ResponseWriter, r *http.Request)

	// (GET /metrics)
	Metrics(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	Ready(w http.ResponseWriter, r *http.Request)

	// (POST /slack/events)
	SlackEvent(w http.ResponseWriter, r *http.Request, params SlackEventParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Live operation middleware
func (siw *ServerInterfaceWrapper) Live(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Live(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Metrics operation middleware
func (siw *ServerInterfaceWrapper) Metrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Metrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ready operation middleware
func (siw *ServerInterfaceWrapper) Ready(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ready(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SlackEvent operation middleware
func (siw *ServerInterfaceWrapper) SlackEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, SlackSignatureScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SlackEventParams

	headers := r.Header

	// ------------- Required header parameter "X-Slack-Request-Timestamp" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Slack-Request-Timestamp")]; found {
		var XSlackRequestTimestamp string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Slack-Request-Timestamp", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Slack-Request-Timestamp", valueList[0], &XSlackRequestTimestamp, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Slack-Request-Timestamp", Err: err})
			return
		}

		params.XSlackRequestTimestamp = XSlackRequestTimestamp

	} else {
		err := fmt.Errorf("Header parameter X-Slack-Request-Timestamp is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Slack-Request-Timestamp", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SlackEvent(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/livez", wrapper.Live)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/metrics", wrapper.Metrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.Ready)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/slack/events", wrapper.SlackEvent)

	return m
}

type LiveRequestObject struct {
}

type LiveResponseObject interface {
	VisitLiveResponse(w http.ResponseWriter) error
}

type Live200Response struct {
}

func (response Live200Response) VisitLiveResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type MetricsRequestObject struct {
}

type MetricsResponseObject interface {
	VisitMetricsResponse(w http.ResponseWriter) error
}

type Metrics200ApplicationopenmetricsTextResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response Metrics200ApplicationopenmetricsTextResponse) VisitMetricsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/openmetrics-text")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type Metrics200ApplicationvndGoogleProtobufResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response Metrics200ApplicationvndGoogleProtobufResponse) VisitMetricsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/vnd.google.protobuf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type Metrics200TextResponse string

func (response Metrics200TextResponse) VisitMetricsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type Metrics500TextResponse string

func (response Metrics500TextResponse) VisitMetricsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(500)

	_, err := w.Write([]byte(response))
	return err
}

type Metrics503TextResponse string

func (response Metrics503TextResponse) VisitMetricsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(503)

	_, err := w.Write([]byte(response))
	return err
}

type ReadyRequestObject struct {
}

type ReadyResponseObject interface {
	VisitReadyResponse(w http.ResponseWriter) error
}

type Ready200Response struct {
}

func (response Ready200Response) VisitReadyResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Ready503Response struct {
}

func (response Ready503Response) VisitReadyResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

type SlackEventRequestObject struct {
	Params SlackEventParams
	Body   *SlackEventJSONRequestBody
}

type SlackEventResponseObject interface {
	VisitSlackEventResponse(w http.ResponseWriter) error
}

type SlackEvent200JSONResponse Acknowledgement

func (response SlackEvent200JSONResponse) VisitSlackEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SlackEvent400Response struct {
}

func (response SlackEvent400Response) VisitSlackEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type SlackEvent401Response struct {
}

func (response SlackEvent401Response) VisitSlackEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type SlackEvent413Response struct {
}

func (response SlackEvent413Response) VisitSlackEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(413)
	return nil
}

type SlackEvent415Response struct {
}

func (response SlackEvent415Response) VisitSlackEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(415)
	return nil
}

type SlackEvent503Response struct {
}

func (response SlackEvent503Response) VisitSlackEventResponse(w http.ResponseWriter) error {
	w.WriteHeader(503)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /livez)
	Live(ctx context.Context, request LiveRequestObject) (LiveResponseObject, error)

	// (GET /metrics)
	Metrics(ctx context.Context, request MetricsRequestObject) (MetricsResponseObject, error)

	// (GET /readyz)
	Ready(ctx context.Context, request ReadyRequestObject) (ReadyResponseObject, error)

	// (POST /slack/events)
	SlackEvent(ctx context.Context, request SlackEventRequestObject) (SlackEventResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Live operation middleware
func (sh *strictHandler) Live(w http.ResponseWriter, r *http.Request) {
	var request LiveRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Live(ctx, request.(LiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Live")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LiveResponseObject); ok {
		if err := validResponse.VisitLiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Metrics operation middleware
func (sh *strictHandler) Metrics(w http.ResponseWriter, r *http.Request) {
	var request MetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Metrics(ctx, request.(MetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Metrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MetricsResponseObject); ok {
		if err := validResponse.VisitMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Ready operation middleware
func (sh *strictHandler) Ready(w http.ResponseWriter, r *http.Request) {
	var request ReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Ready(ctx, request.(ReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ready")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadyResponseObject); ok {
		if err := validResponse.VisitReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SlackEvent operation middleware
func (sh *strictHandler) SlackEvent(w http.ResponseWriter, r *http.Request, params SlackEventParams) {
	var request SlackEventRequestObject

	request.Params = params

	var body SlackEventJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SlackEvent(ctx, request.(SlackEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SlackEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SlackEventResponseObject); ok {
		if err := validResponse.VisitSlackEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
