// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const getRecord = `-- name: GetRecord :one
SELECT value FROM records WHERE key = ?
`

func (q *Queries) GetRecord(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getRecord, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const putRecord = `-- name: PutRecord :exec
INSERT INTO records (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type PutRecordParams struct {
	Key   string
	Value []byte
}

func (q *Queries) PutRecord(ctx context.Context, arg PutRecordParams) error {
	_, err := q.db.ExecContext(ctx, putRecord, arg.Key, arg.Value)
	return err
}

const scanRecords = `-- name: ScanRecords :many
SELECT key, value FROM records WHERE key >= ? AND key < ? ORDER BY key
`

type ScanRecordsParams struct {
	Key   string
	Key_2 string
}

func (q *Queries) ScanRecords(ctx context.Context, arg ScanRecordsParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, scanRecords, arg.Key, arg.Key_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
