// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	HubspotEventOperation OperationName = "HubspotEvent"
	LiveOperation         OperationName = "Live"
	MetricsOperation      OperationName = "Metrics"
	ReadyOperation        OperationName = "Ready"
	SlackEventOperation   OperationName = "SlackEvent"
)
