// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// SlackEventParams is parameters of slackEvent operation.
type SlackEventParams struct {
	XSlackRequestTimestamp string
}

func unpackSlackEventParams(packed middleware.Parameters) (params SlackEventParams) {
	{
		key := middleware.ParameterKey{
			Name: "X-Slack-Request-Timestamp",
			In:   "header",
		}
		params.XSlackRequestTimestamp = packed[key].(string)
	}
	return params
}

func decodeSlackEventParams(args [0]string, argsEscaped bool, r *http.Request) (params SlackEventParams, _ error) {
	h := uri.NewHeaderDecoder(r.Header)
	// Decode header: X-Slack-Request-Timestamp.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Slack-Request-Timestamp",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.XSlackRequestTimestamp = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Slack-Request-Timestamp",
			In:   "header",
			Err:  err,
		}
	}
	return params, nil
}
