// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"

	"github.com/go-faster/jx"
)

// Ref: #/components/schemas/Acknowledgement
type Acknowledgement struct {
	Challenge OptString `json:"challenge"`
}

// GetChallenge returns the value of Challenge.
func (s *Acknowledgement) GetChallenge() OptString {
	return s.Challenge
}

// SetChallenge sets the value of Challenge.
func (s *Acknowledgement) SetChallenge(val OptString) {
	s.Challenge = val
}

func (*Acknowledgement) slackEventRes() {}

// Ref: #/components/schemas/Envelope
type Envelope struct {
	Challenge OptString     `json:"challenge"`
	Event     OptSlackEvent `json:"event"`
	EventID   OptString     `json:"event_id"`
	TeamID    OptString     `json:"team_id"`
	Type      string        `json:"type"`
}

// GetChallenge returns the value of Challenge.
func (s *Envelope) GetChallenge() OptString {
	return s.Challenge
}

// GetEvent returns the value of Event.
func (s *Envelope) GetEvent() OptSlackEvent {
	return s.Event
}

// GetEventID returns the value of EventID.
func (s *Envelope) GetEventID() OptString {
	return s.EventID
}

// GetTeamID returns the value of TeamID.
func (s *Envelope) GetTeamID() OptString {
	return s.TeamID
}

// GetType returns the value of Type.
func (s *Envelope) GetType() string {
	return s.Type
}

// SetChallenge sets the value of Challenge.
func (s *Envelope) SetChallenge(val OptString) {
	s.Challenge = val
}

// SetEvent sets the value of Event.
func (s *Envelope) SetEvent(val OptSlackEvent) {
	s.Event = val
}

// SetEventID sets the value of EventID.
func (s *Envelope) SetEventID(val OptString) {
	s.EventID = val
}

// SetTeamID sets the value of TeamID.
func (s *Envelope) SetTeamID(val OptString) {
	s.TeamID = val
}

// SetType sets the value of Type.
func (s *Envelope) SetType(val string) {
	s.Type = val
}

// HubSpot CRM webhook event. Supports legacy ticket.* and generic object.* subscription types. Generic
// ticket events identify tickets with objectTypeId 0-5. Unknown fields are retained for forward
// compatibility. Property-change events include propertyName and propertyValue; other event-specific
// fields are optional. Event IDs alone are not guaranteed unique, and deliveries may be duplicated or
// arrive out of order.
// Ref: #/components/schemas/HubSpotWebhookEvent
type HubSpotWebhookEvent struct {
	// Event identifier; not a globally unique deduplication key.
	EventId OptInt64 `json:"eventId"`
	// Webhook subscription identifier.
	SubscriptionId OptInt64 `json:"subscriptionId"`
	// HubSpot account identifier.
	PortalId int64 `json:"portalId"`
	// HubSpot app identifier.
	AppId OptInt64 `json:"appId"`
	// Event occurrence time in milliseconds since the Unix epoch.
	OccurredAt int64 `json:"occurredAt"`
	// Delivery attempt number.
	AttemptNumber OptInt `json:"attemptNumber"`
	// CRM record identifier; the ticket ID for ticket events.
	ObjectId int64 `json:"objectId"`
	// CRM object type for generic events; 0-5 denotes tickets.
	ObjectTypeId OptString `json:"objectTypeId"`
	// Event type, kept open to support legacy and generic formats.
	SubscriptionType string `json:"subscriptionType"`
	// Internal property name for a property-change event.
	PropertyName OptString `json:"propertyName"`
	// New property value; may be empty when cleared.
	PropertyValue OptString `json:"propertyValue"`
	// Source of the change, when provided by HubSpot.
	ChangeSource OptString `json:"changeSource"`
	// Source identifier, when provided by HubSpot.
	SourceId        OptString `json:"sourceId"`
	AdditionalProps HubSpotWebhookEventAdditional
}

// GetEventId returns the value of EventId.
func (s *HubSpotWebhookEvent) GetEventId() OptInt64 {
	return s.EventId
}

// GetSubscriptionId returns the value of SubscriptionId.
func (s *HubSpotWebhookEvent) GetSubscriptionId() OptInt64 {
	return s.SubscriptionId
}

// GetPortalId returns the value of PortalId.
func (s *HubSpotWebhookEvent) GetPortalId() int64 {
	return s.PortalId
}

// GetAppId returns the value of AppId.
func (s *HubSpotWebhookEvent) GetAppId() OptInt64 {
	return s.AppId
}

// GetOccurredAt returns the value of OccurredAt.
func (s *HubSpotWebhookEvent) GetOccurredAt() int64 {
	return s.OccurredAt
}

// GetAttemptNumber returns the value of AttemptNumber.
func (s *HubSpotWebhookEvent) GetAttemptNumber() OptInt {
	return s.AttemptNumber
}

// GetObjectId returns the value of ObjectId.
func (s *HubSpotWebhookEvent) GetObjectId() int64 {
	return s.ObjectId
}

// GetObjectTypeId returns the value of ObjectTypeId.
func (s *HubSpotWebhookEvent) GetObjectTypeId() OptString {
	return s.ObjectTypeId
}

// GetSubscriptionType returns the value of SubscriptionType.
func (s *HubSpotWebhookEvent) GetSubscriptionType() string {
	return s.SubscriptionType
}

// GetPropertyName returns the value of PropertyName.
func (s *HubSpotWebhookEvent) GetPropertyName() OptString {
	return s.PropertyName
}

// GetPropertyValue returns the value of PropertyValue.
func (s *HubSpotWebhookEvent) GetPropertyValue() OptString {
	return s.PropertyValue
}

// GetChangeSource returns the value of ChangeSource.
func (s *HubSpotWebhookEvent) GetChangeSource() OptString {
	return s.ChangeSource
}

// GetSourceId returns the value of SourceId.
func (s *HubSpotWebhookEvent) GetSourceId() OptString {
	return s.SourceId
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *HubSpotWebhookEvent) GetAdditionalProps() HubSpotWebhookEventAdditional {
	return s.AdditionalProps
}

// SetEventId sets the value of EventId.
func (s *HubSpotWebhookEvent) SetEventId(val OptInt64) {
	s.EventId = val
}

// SetSubscriptionId sets the value of SubscriptionId.
func (s *HubSpotWebhookEvent) SetSubscriptionId(val OptInt64) {
	s.SubscriptionId = val
}

// SetPortalId sets the value of PortalId.
func (s *HubSpotWebhookEvent) SetPortalId(val int64) {
	s.PortalId = val
}

// SetAppId sets the value of AppId.
func (s *HubSpotWebhookEvent) SetAppId(val OptInt64) {
	s.AppId = val
}

// SetOccurredAt sets the value of OccurredAt.
func (s *HubSpotWebhookEvent) SetOccurredAt(val int64) {
	s.OccurredAt = val
}

// SetAttemptNumber sets the value of AttemptNumber.
func (s *HubSpotWebhookEvent) SetAttemptNumber(val OptInt) {
	s.AttemptNumber = val
}

// SetObjectId sets the value of ObjectId.
func (s *HubSpotWebhookEvent) SetObjectId(val int64) {
	s.ObjectId = val
}

// SetObjectTypeId sets the value of ObjectTypeId.
func (s *HubSpotWebhookEvent) SetObjectTypeId(val OptString) {
	s.ObjectTypeId = val
}

// SetSubscriptionType sets the value of SubscriptionType.
func (s *HubSpotWebhookEvent) SetSubscriptionType(val string) {
	s.SubscriptionType = val
}

// SetPropertyName sets the value of PropertyName.
func (s *HubSpotWebhookEvent) SetPropertyName(val OptString) {
	s.PropertyName = val
}

// SetPropertyValue sets the value of PropertyValue.
func (s *HubSpotWebhookEvent) SetPropertyValue(val OptString) {
	s.PropertyValue = val
}

// SetChangeSource sets the value of ChangeSource.
func (s *HubSpotWebhookEvent) SetChangeSource(val OptString) {
	s.ChangeSource = val
}

// SetSourceId sets the value of SourceId.
func (s *HubSpotWebhookEvent) SetSourceId(val OptString) {
	s.SourceId = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *HubSpotWebhookEvent) SetAdditionalProps(val HubSpotWebhookEventAdditional) {
	s.AdditionalProps = val
}

type HubSpotWebhookEventAdditional map[string]jx.Raw

func (s *HubSpotWebhookEventAdditional) init() HubSpotWebhookEventAdditional {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// HubspotEventBadRequest is response for HubspotEvent operation.
type HubspotEventBadRequest struct{}

func (*HubspotEventBadRequest) hubspotEventRes() {}

// HubspotEventNotImplemented is response for HubspotEvent operation.
type HubspotEventNotImplemented struct{}

func (*HubspotEventNotImplemented) hubspotEventRes() {}

// HubspotEventRequestEntityTooLarge is response for HubspotEvent operation.
type HubspotEventRequestEntityTooLarge struct{}

func (*HubspotEventRequestEntityTooLarge) hubspotEventRes() {}

// HubspotEventUnsupportedMediaType is response for HubspotEvent operation.
type HubspotEventUnsupportedMediaType struct{}

func (*HubspotEventUnsupportedMediaType) hubspotEventRes() {}

// LiveOK is response for Live operation.
type LiveOK struct{}

type MetricsInternalServerError struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s MetricsInternalServerError) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*MetricsInternalServerError) metricsRes() {}

type MetricsOKApplicationOpenmetricsText struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s MetricsOKApplicationOpenmetricsText) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*MetricsOKApplicationOpenmetricsText) metricsRes() {}

type MetricsOKApplicationVndGoogleProtobuf struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s MetricsOKApplicationVndGoogleProtobuf) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*MetricsOKApplicationVndGoogleProtobuf) metricsRes() {}

type MetricsOKTextPlain struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s MetricsOKTextPlain) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*MetricsOKTextPlain) metricsRes() {}

type MetricsServiceUnavailable struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s MetricsServiceUnavailable) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*MetricsServiceUnavailable) metricsRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSlackEvent returns new OptSlackEvent with value set to v.
func NewOptSlackEvent(v SlackEvent) OptSlackEvent {
	return OptSlackEvent{
		Value: v,
		Set:   true,
	}
}

// OptSlackEvent is optional SlackEvent.
type OptSlackEvent struct {
	Value SlackEvent
	Set   bool
}

// IsSet returns true if OptSlackEvent was set.
func (o OptSlackEvent) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSlackEvent) Reset() {
	var v SlackEvent
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSlackEvent) SetTo(v SlackEvent) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSlackEvent) Get() (v SlackEvent, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSlackEvent) Or(d SlackEvent) SlackEvent {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSlackMessage returns new OptSlackMessage with value set to v.
func NewOptSlackMessage(v SlackMessage) OptSlackMessage {
	return OptSlackMessage{
		Value: v,
		Set:   true,
	}
}

// OptSlackMessage is optional SlackMessage.
type OptSlackMessage struct {
	Value SlackMessage
	Set   bool
}

// IsSet returns true if OptSlackMessage was set.
func (o OptSlackMessage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSlackMessage) Reset() {
	var v SlackMessage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSlackMessage) SetTo(v SlackMessage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSlackMessage) Get() (v SlackMessage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSlackMessage) Or(d SlackMessage) SlackMessage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// ReadyOK is response for Ready operation.
type ReadyOK struct{}

func (*ReadyOK) readyRes() {}

// ReadyServiceUnavailable is response for Ready operation.
type ReadyServiceUnavailable struct{}

func (*ReadyServiceUnavailable) readyRes() {}

// Ref: #/components/schemas/SlackEvent
type SlackEvent struct {
	BotID           OptString       `json:"bot_id"`
	Channel         OptString       `json:"channel"`
	ChannelType     OptString       `json:"channel_type"`
	DeletedTs       OptString       `json:"deleted_ts"`
	Message         OptSlackMessage `json:"message"`
	PreviousMessage OptSlackMessage `json:"previous_message"`
	Subtype         OptString       `json:"subtype"`
	Text            OptString       `json:"text"`
	ThreadTs        OptString       `json:"thread_ts"`
	Ts              OptString       `json:"ts"`
	Type            string          `json:"type"`
	User            OptString       `json:"user"`
}

// GetBotID returns the value of BotID.
func (s *SlackEvent) GetBotID() OptString {
	return s.BotID
}

// GetChannel returns the value of Channel.
func (s *SlackEvent) GetChannel() OptString {
	return s.Channel
}

// GetChannelType returns the value of ChannelType.
func (s *SlackEvent) GetChannelType() OptString {
	return s.ChannelType
}

// GetDeletedTs returns the value of DeletedTs.
func (s *SlackEvent) GetDeletedTs() OptString {
	return s.DeletedTs
}

// GetMessage returns the value of Message.
func (s *SlackEvent) GetMessage() OptSlackMessage {
	return s.Message
}

// GetPreviousMessage returns the value of PreviousMessage.
func (s *SlackEvent) GetPreviousMessage() OptSlackMessage {
	return s.PreviousMessage
}

// GetSubtype returns the value of Subtype.
func (s *SlackEvent) GetSubtype() OptString {
	return s.Subtype
}

// GetText returns the value of Text.
func (s *SlackEvent) GetText() OptString {
	return s.Text
}

// GetThreadTs returns the value of ThreadTs.
func (s *SlackEvent) GetThreadTs() OptString {
	return s.ThreadTs
}

// GetTs returns the value of Ts.
func (s *SlackEvent) GetTs() OptString {
	return s.Ts
}

// GetType returns the value of Type.
func (s *SlackEvent) GetType() string {
	return s.Type
}

// GetUser returns the value of User.
func (s *SlackEvent) GetUser() OptString {
	return s.User
}

// SetBotID sets the value of BotID.
func (s *SlackEvent) SetBotID(val OptString) {
	s.BotID = val
}

// SetChannel sets the value of Channel.
func (s *SlackEvent) SetChannel(val OptString) {
	s.Channel = val
}

// SetChannelType sets the value of ChannelType.
func (s *SlackEvent) SetChannelType(val OptString) {
	s.ChannelType = val
}

// SetDeletedTs sets the value of DeletedTs.
func (s *SlackEvent) SetDeletedTs(val OptString) {
	s.DeletedTs = val
}

// SetMessage sets the value of Message.
func (s *SlackEvent) SetMessage(val OptSlackMessage) {
	s.Message = val
}

// SetPreviousMessage sets the value of PreviousMessage.
func (s *SlackEvent) SetPreviousMessage(val OptSlackMessage) {
	s.PreviousMessage = val
}

// SetSubtype sets the value of Subtype.
func (s *SlackEvent) SetSubtype(val OptString) {
	s.Subtype = val
}

// SetText sets the value of Text.
func (s *SlackEvent) SetText(val OptString) {
	s.Text = val
}

// SetThreadTs sets the value of ThreadTs.
func (s *SlackEvent) SetThreadTs(val OptString) {
	s.ThreadTs = val
}

// SetTs sets the value of Ts.
func (s *SlackEvent) SetTs(val OptString) {
	s.Ts = val
}

// SetType sets the value of Type.
func (s *SlackEvent) SetType(val string) {
	s.Type = val
}

// SetUser sets the value of User.
func (s *SlackEvent) SetUser(val OptString) {
	s.User = val
}

// SlackEventBadRequest is response for SlackEvent operation.
type SlackEventBadRequest struct{}

func (*SlackEventBadRequest) slackEventRes() {}

// SlackEventRequestEntityTooLarge is response for SlackEvent operation.
type SlackEventRequestEntityTooLarge struct{}

func (*SlackEventRequestEntityTooLarge) slackEventRes() {}

// SlackEventServiceUnavailable is response for SlackEvent operation.
type SlackEventServiceUnavailable struct{}

func (*SlackEventServiceUnavailable) slackEventRes() {}

// SlackEventUnauthorized is response for SlackEvent operation.
type SlackEventUnauthorized struct{}

func (*SlackEventUnauthorized) slackEventRes() {}

// SlackEventUnsupportedMediaType is response for SlackEvent operation.
type SlackEventUnsupportedMediaType struct{}

func (*SlackEventUnsupportedMediaType) slackEventRes() {}

// Ref: #/components/schemas/SlackMessage
type SlackMessage struct {
	BotID    OptString `json:"bot_id"`
	Subtype  OptString `json:"subtype"`
	Text     OptString `json:"text"`
	ThreadTs OptString `json:"thread_ts"`
	Ts       OptString `json:"ts"`
	User     OptString `json:"user"`
}

// GetBotID returns the value of BotID.
func (s *SlackMessage) GetBotID() OptString {
	return s.BotID
}

// GetSubtype returns the value of Subtype.
func (s *SlackMessage) GetSubtype() OptString {
	return s.Subtype
}

// GetText returns the value of Text.
func (s *SlackMessage) GetText() OptString {
	return s.Text
}

// GetThreadTs returns the value of ThreadTs.
func (s *SlackMessage) GetThreadTs() OptString {
	return s.ThreadTs
}

// GetTs returns the value of Ts.
func (s *SlackMessage) GetTs() OptString {
	return s.Ts
}

// GetUser returns the value of User.
func (s *SlackMessage) GetUser() OptString {
	return s.User
}

// SetBotID sets the value of BotID.
func (s *SlackMessage) SetBotID(val OptString) {
	s.BotID = val
}

// SetSubtype sets the value of Subtype.
func (s *SlackMessage) SetSubtype(val OptString) {
	s.Subtype = val
}

// SetText sets the value of Text.
func (s *SlackMessage) SetText(val OptString) {
	s.Text = val
}

// SetThreadTs sets the value of ThreadTs.
func (s *SlackMessage) SetThreadTs(val OptString) {
	s.ThreadTs = val
}

// SetTs sets the value of Ts.
func (s *SlackMessage) SetTs(val OptString) {
	s.Ts = val
}

// SetUser sets the value of User.
func (s *SlackMessage) SetUser(val OptString) {
	s.User = val
}

type SlackSignature struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *SlackSignature) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *SlackSignature) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *SlackSignature) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *SlackSignature) SetRoles(val []string) {
	s.Roles = val
}
