// Code generated by ogen, DO NOT EDIT.
package api

type HubspotEventRes interface {
	hubspotEventRes()
}

type MetricsRes interface {
	metricsRes()
}

type ReadyRes interface {
	readyRes()
}

type SlackEventRes interface {
	slackEventRes()
}
