// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func encodeHubspotEventResponse(response HubspotEventRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *HubspotEventBadRequest:
		w.WriteHeader(400)

		return nil

	case *HubspotEventRequestEntityTooLarge:
		w.WriteHeader(413)

		return nil

	case *HubspotEventUnsupportedMediaType:
		w.WriteHeader(415)

		return nil

	case *HubspotEventNotImplemented:
		w.WriteHeader(501)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeLiveResponse(response *LiveOK, w http.ResponseWriter) error {
	w.WriteHeader(200)

	return nil
}

func encodeMetricsResponse(response MetricsRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *MetricsOKApplicationOpenmetricsText:
		w.Header().Set("Content-Type", "application/openmetrics-text")
		w.WriteHeader(200)

		writer := w
		if closer, ok := response.Data.(io.Closer); ok {
			defer closer.Close()
		}
		if _, err := io.Copy(writer, response); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *MetricsOKApplicationVndGoogleProtobuf:
		w.Header().Set("Content-Type", "application/vnd.google.protobuf")
		w.WriteHeader(200)

		writer := w
		if closer, ok := response.Data.(io.Closer); ok {
			defer closer.Close()
		}
		if _, err := io.Copy(writer, response); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *MetricsOKTextPlain:
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.WriteHeader(200)

		writer := w
		if closer, ok := response.Data.(io.Closer); ok {
			defer closer.Close()
		}
		if _, err := io.Copy(writer, response); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *MetricsInternalServerError:
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.WriteHeader(500)

		writer := w
		if closer, ok := response.Data.(io.Closer); ok {
			defer closer.Close()
		}
		if _, err := io.Copy(writer, response); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *MetricsServiceUnavailable:
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.WriteHeader(503)

		writer := w
		if closer, ok := response.Data.(io.Closer); ok {
			defer closer.Close()
		}
		if _, err := io.Copy(writer, response); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeReadyResponse(response ReadyRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *ReadyOK:
		w.WriteHeader(200)

		return nil

	case *ReadyServiceUnavailable:
		w.WriteHeader(503)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}

func encodeSlackEventResponse(response SlackEventRes, w http.ResponseWriter) error {
	switch response := response.(type) {
	case *Acknowledgement:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.WriteHeader(200)

		e := new(jx.Encoder)
		response.Encode(e)
		if _, err := e.WriteTo(w); err != nil {
			return errors.Wrap(err, "write")
		}

		return nil

	case *SlackEventBadRequest:
		w.WriteHeader(400)

		return nil

	case *SlackEventUnauthorized:
		w.WriteHeader(401)

		return nil

	case *SlackEventRequestEntityTooLarge:
		w.WriteHeader(413)

		return nil

	case *SlackEventUnsupportedMediaType:
		w.WriteHeader(415)

		return nil

	case *SlackEventServiceUnavailable:
		w.WriteHeader(503)

		return nil

	default:
		return errors.Errorf("unexpected response type: %T", response)
	}
}
