// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleSlackSignature handles SlackSignature security.
	// Slack v0 HMAC SHA-256 signature over version, timestamp, and exact raw request body; timestamps must
	// be within five minutes.
	HandleSlackSignature(ctx context.Context, operationName OperationName, t SlackSignature) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesSlackSignature is a private map storing roles per operation.
var operationRolesSlackSignature = map[string][]string{
	SlackEventOperation: []string{},
}

// GetRolesForSlackSignature returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForSlackSignature(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForSlackSignature(operation string) []string {
	roles, ok := operationRolesSlackSignature[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securitySlackSignature(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t SlackSignature
	const parameterName = "X-Slack-Signature"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesSlackSignature[operationName]
	rctx, err := s.sec.HandleSlackSignature(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}
