// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// HubspotEvent implements hubspotEvent operation.
	//
	// Placeholder for HubSpot webhook batches. No events are processed or acknowledged as accepted yet.
	// Signature verification and durable refresh scheduling must be implemented before enabling HubSpot
	// subscriptions.
	//
	// POST /hubspot/events
	HubspotEvent(ctx context.Context, req []HubSpotWebhookEvent) (HubspotEventRes, error)
	// Live implements live operation.
	//
	// GET /livez
	Live(ctx context.Context) error
	// Metrics implements metrics operation.
	//
	// GET /metrics
	Metrics(ctx context.Context) (MetricsRes, error)
	// Ready implements ready operation.
	//
	// GET /readyz
	Ready(ctx context.Context) (ReadyRes, error)
	// SlackEvent implements slackEvent operation.
	//
	// Authenticated Slack Events API envelopes. Raw-body signature verification precedes JSON decoding.
	//
	// POST /slack/events
	SlackEvent(ctx context.Context, req *Envelope, params SlackEventParams) (SlackEventRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
