// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
)

const createDefaultSchema = `-- name: CreateDefaultSchema :exec
CREATE SCHEMA IF NOT EXISTS slack_hubspot
`

func (q *Queries) CreateDefaultSchema(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDefaultSchema)
	return err
}

const createRecords = `-- name: CreateRecords :exec
CREATE TABLE IF NOT EXISTS records (
    key TEXT PRIMARY KEY NOT NULL,
    value BYTEA NOT NULL
)
`

func (q *Queries) CreateRecords(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createRecords)
	return err
}

const getRecord = `-- name: GetRecord :one
SELECT value FROM records WHERE key = $1
`

func (q *Queries) GetRecord(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getRecord, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const putRecord = `-- name: PutRecord :exec
INSERT INTO records (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type PutRecordParams struct {
	Key   string
	Value []byte
}

func (q *Queries) PutRecord(ctx context.Context, arg PutRecordParams) error {
	_, err := q.db.ExecContext(ctx, putRecord, arg.Key, arg.Value)
	return err
}

const scanRecords = `-- name: ScanRecords :many
SELECT key, value FROM records WHERE key >= $1 AND key < $2 ORDER BY key
`

type ScanRecordsParams struct {
	Key   string
	Key_2 string
}

func (q *Queries) ScanRecords(ctx context.Context, arg ScanRecordsParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, scanRecords, arg.Key, arg.Key_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schemaExists = `-- name: SchemaExists :one
SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = $1)
`

func (q *Queries) SchemaExists(ctx context.Context, nspname string) (bool, error) {
	row := q.db.QueryRowContext(ctx, schemaExists, nspname)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
